# Generated by Django 4.2 on 2023-05-07 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nascar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="make",
            field=models.CharField(default="N/A", max_length=32),
        ),
        migrations.AlterField(
            model_name="driver",
            name="salary",
            field=models.IntegerField(default=3000),
        ),
        migrations.AlterField(
            model_name="driver",
            name="sponsor",
            field=models.CharField(default="N/A", max_length=64),
        ),
        migrations.AlterField(
            model_name="driver",
            name="team",
            field=models.CharField(default="N/A", max_length=64),
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="date created"
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="date last updated"
                    ),
                ),
                ("name", models.CharField(default="N/A", max_length=32)),
                ("configuration", models.CharField(default="Oval", max_length=16)),
                ("track_length", models.FloatField(default=0.0)),
                ("banking", models.CharField(default="N/A", max_length=64)),
                ("location", models.CharField(default="N/A", max_length=64)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
