# Generated by Django 4.2 on 2023-05-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nascar", "0002_alter_driver_make_alter_driver_salary_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="track",
            old_name="banking",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="track",
            old_name="location",
            new_name="owner",
        ),
        migrations.AddField(
            model_name="track",
            name="state",
            field=models.CharField(default="N/A", max_length=64),
        ),
    ]
