# Generated by Django 4.2 on 2023-04-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nascar", "0003_alter_driver_unique_together_driver2"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Driver2",
        ),
    ]
